name: Build and Publish Release

on:
  workflow_dispatch:

permissions:
  contents: write

env:
  executable: PoBoy
  target: local

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-26.04
            artifact: linux

          - os: macos-26
            artifact: macos

          - os: windows-latest
            artifact: windows

          - os: ubuntu-26.04
            artifact: web

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash
    
    steps:
      - uses: actions/checkout@v6

      - name: Install SDL3 Dependencies
        if: matrix.artifact == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install build-essential git make \
          pkg-config cmake ninja-build gnome-desktop-testing libasound2-dev libpulse-dev \
          libaudio-dev libfribidi-dev libjack-dev libsndio-dev libx11-dev libxext-dev \
          libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libxtst-dev \
          libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev \
          libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev libthai-dev libusb-1.0-0-dev \
          libpipewire-0.3-dev libwayland-dev libdecor-0-dev liburing-dev

      - name: Configure LLVM Clang
        if: matrix.artifact == 'macos'
        run: |
          brew install lld@20
          echo "$(brew --prefix llvm@20)/bin" >> $GITHUB_PATH
          echo "SDKROOT=$(xcrun --sdk macosx --show-sdk-path)" >> $GITHUB_ENV

      - name: Configure Web Cross Compiler
        if: matrix.artifact == 'web'
        run: |
          cd ~
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          echo "$(pwd)" >> $GITHUB_PATH
          echo "EMSDK=$(pwd)" >> $GITHUB_ENV
          echo "target=${{ matrix.artifact }}" >> $GITHUB_ENV

      - name: Build
        run: python3 dmg_build.py -m release -t ${{ env.target }} ${{ env.executable }}

      - name: Package
        run: |
          mkdir artifacts
          zip -j artifacts/${{ env.executable }}-${{ matrix.artifact }}.zip build/${{ env.target }}/bin/*

      - uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.artifact }}
          path: artifacts/*

  release:
    needs: build

    runs-on: ubuntu-latest

    env:
      tag: beta

    steps:
      - uses: actions/checkout@v6

      - name: Delete Latest Release
        run: gh release delete ${{ env.tag }} --cleanup-tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/download-artifact@v6
        with:
          path: artifacts

      - name: Publish Release
        uses: softprops/action-gh-release@v3
        with:
          name: ${{ github.ref_name }}
          tag_name: ${{ env.tag }}
          make_latest: true
          target_commitish: ${{ github.sha }}
          files: |
            artifacts/**/*